# Soulbound Configuration

# Chance (0.0 to 1.0) that the Soulbound enchantment will be removed from an item after death
# 0.0 = never remove, 1.0 = always remove
soulbound-removal-chance: 0.0

# Enable debug logging
debug: false

