name: Soulbound
version: '${version}'
main: com.japherwocky.soulbound.SoulboundPlugin
api-version: '1.21'
authors: [japherwocky]
description: A Minecraft enchantment for keeping items when you die.
website: https://github.com/japherwocky/Soulbound

commands:
  soulbound:
    description: Soulbound plugin commands
    usage: /soulbound [reload|info]
    permission: soulbound.command

permissions:
  soulbound.command:
    description: Allows access to Soulbound commands
    default: op

