name: Soulbound
version: 1.0.0
main: info.tehnut.soulbound.SoulboundPlugin
api-version: 1.17
description: An enchantment that will retain items upon death
author: TehNut
website: https://github.com/japherwocky/Soulbound

commands:
  soulbound:
    description: Soulbound plugin commands
    usage: /soulbound [reload|info]
    permission: soulbound.command

permissions:
  soulbound.command:
    description: Allows access to Soulbound commands
    default: op
  soulbound.enchant:
    description: Allows applying the Soulbound enchantment
    default: op

